FROM mcr.microsoft.com/dotnet/sdk:6.0 as base
WORKDIR /app
EXPOSE 80
EXPOSE 443
RUN dotnet dev-certs https -ep ${HOME}/.aspnet/https/PixCharge.SPA.pfx -p ${HOME}/.aspnet/https
RUN dotnet dev-certs https --trust

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS publish
WORKDIR /src
COPY . .
RUN dotnet publish -c Release -o /app/publish  /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as final
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Production
ENV ASPNETCORE_URLS=http://+80;https://+443;
ENV ASPNETCORE_HTTPS_PORT=443

COPY --from=base /root ../root
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PixCharge.SPA.dll"]